spring.application.name=ST5

server.port=8089

#Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.profiles.active= dev

# session time out
server.servlet.session.timeout=30m