spring.application.name=ST5

server.port=8089

#Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/st5
spring.datasource.username=root
spring.datasource.password=itc@123
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=TRACE


# session time out
server.servlet.session.timeout=30m